// flow-typed signature: f1075849a2d56105dfa68a016ac7eb3b
// flow-typed version: <<STUB>>/jscodeshift_v0.3.30/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jscodeshift'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jscodeshift' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jscodeshift/dist/Collection' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/collections/index' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/collections/JSXElement' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/collections/Node' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/collections/VariableDeclarator' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/core' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/getParser' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/ignoreFiles' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/jsx/AstWrapper' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/jsx/components/CallExpression' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/jsx/components/Identifier' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/jsx/components/index' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/jsx/components/Literal' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/jsx/components/MemberExpression' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/jsx/components/VariableDeclarator' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/jsx/ensure' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/jsx/index' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/jsx/util' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/matchNode' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/Runner' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/template' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/testUtils' {
  declare module.exports: any;
}

declare module 'jscodeshift/dist/Worker' {
  declare module.exports: any;
}

declare module 'jscodeshift/docs/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'jscodeshift/docs/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'jscodeshift/docs/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'jscodeshift/parser/babylon' {
  declare module.exports: any;
}

declare module 'jscodeshift/parser/flow' {
  declare module.exports: any;
}

declare module 'jscodeshift/utils/requirePackage' {
  declare module.exports: any;
}

declare module 'jscodeshift/utils/testUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jscodeshift/dist/Collection.js' {
  declare module.exports: $Exports<'jscodeshift/dist/Collection'>;
}
declare module 'jscodeshift/dist/collections/index.js' {
  declare module.exports: $Exports<'jscodeshift/dist/collections/index'>;
}
declare module 'jscodeshift/dist/collections/JSXElement.js' {
  declare module.exports: $Exports<'jscodeshift/dist/collections/JSXElement'>;
}
declare module 'jscodeshift/dist/collections/Node.js' {
  declare module.exports: $Exports<'jscodeshift/dist/collections/Node'>;
}
declare module 'jscodeshift/dist/collections/VariableDeclarator.js' {
  declare module.exports: $Exports<'jscodeshift/dist/collections/VariableDeclarator'>;
}
declare module 'jscodeshift/dist/core.js' {
  declare module.exports: $Exports<'jscodeshift/dist/core'>;
}
declare module 'jscodeshift/dist/getParser.js' {
  declare module.exports: $Exports<'jscodeshift/dist/getParser'>;
}
declare module 'jscodeshift/dist/ignoreFiles.js' {
  declare module.exports: $Exports<'jscodeshift/dist/ignoreFiles'>;
}
declare module 'jscodeshift/dist/jsx/AstWrapper.js' {
  declare module.exports: $Exports<'jscodeshift/dist/jsx/AstWrapper'>;
}
declare module 'jscodeshift/dist/jsx/components/CallExpression.js' {
  declare module.exports: $Exports<'jscodeshift/dist/jsx/components/CallExpression'>;
}
declare module 'jscodeshift/dist/jsx/components/Identifier.js' {
  declare module.exports: $Exports<'jscodeshift/dist/jsx/components/Identifier'>;
}
declare module 'jscodeshift/dist/jsx/components/index.js' {
  declare module.exports: $Exports<'jscodeshift/dist/jsx/components/index'>;
}
declare module 'jscodeshift/dist/jsx/components/Literal.js' {
  declare module.exports: $Exports<'jscodeshift/dist/jsx/components/Literal'>;
}
declare module 'jscodeshift/dist/jsx/components/MemberExpression.js' {
  declare module.exports: $Exports<'jscodeshift/dist/jsx/components/MemberExpression'>;
}
declare module 'jscodeshift/dist/jsx/components/VariableDeclarator.js' {
  declare module.exports: $Exports<'jscodeshift/dist/jsx/components/VariableDeclarator'>;
}
declare module 'jscodeshift/dist/jsx/ensure.js' {
  declare module.exports: $Exports<'jscodeshift/dist/jsx/ensure'>;
}
declare module 'jscodeshift/dist/jsx/index.js' {
  declare module.exports: $Exports<'jscodeshift/dist/jsx/index'>;
}
declare module 'jscodeshift/dist/jsx/util.js' {
  declare module.exports: $Exports<'jscodeshift/dist/jsx/util'>;
}
declare module 'jscodeshift/dist/matchNode.js' {
  declare module.exports: $Exports<'jscodeshift/dist/matchNode'>;
}
declare module 'jscodeshift/dist/Runner.js' {
  declare module.exports: $Exports<'jscodeshift/dist/Runner'>;
}
declare module 'jscodeshift/dist/template.js' {
  declare module.exports: $Exports<'jscodeshift/dist/template'>;
}
declare module 'jscodeshift/dist/testUtils.js' {
  declare module.exports: $Exports<'jscodeshift/dist/testUtils'>;
}
declare module 'jscodeshift/dist/Worker.js' {
  declare module.exports: $Exports<'jscodeshift/dist/Worker'>;
}
declare module 'jscodeshift/docs/scripts/linenumber.js' {
  declare module.exports: $Exports<'jscodeshift/docs/scripts/linenumber'>;
}
declare module 'jscodeshift/docs/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'jscodeshift/docs/scripts/prettify/lang-css'>;
}
declare module 'jscodeshift/docs/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'jscodeshift/docs/scripts/prettify/prettify'>;
}
declare module 'jscodeshift/index' {
  declare module.exports: $Exports<'jscodeshift'>;
}
declare module 'jscodeshift/index.js' {
  declare module.exports: $Exports<'jscodeshift'>;
}
declare module 'jscodeshift/parser/babylon.js' {
  declare module.exports: $Exports<'jscodeshift/parser/babylon'>;
}
declare module 'jscodeshift/parser/flow.js' {
  declare module.exports: $Exports<'jscodeshift/parser/flow'>;
}
declare module 'jscodeshift/utils/requirePackage.js' {
  declare module.exports: $Exports<'jscodeshift/utils/requirePackage'>;
}
declare module 'jscodeshift/utils/testUtils.js' {
  declare module.exports: $Exports<'jscodeshift/utils/testUtils'>;
}
